// <auto-generated />
using System;
using Blogging.NewDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blogging.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20190916090155_NewBlogsAndPostsChanges2")]
    partial class NewBlogsAndPostsChanges2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blogging.NewDb.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("BlogId");

                    b.ToTable("Blog");

                    b.HasData(
                        new
                        {
                            BlogId = 4,
                            Url = "http://test1.dk"
                        },
                        new
                        {
                            BlogId = 6,
                            Url = "http://test3.dk"
                        },
                        new
                        {
                            BlogId = 7,
                            Url = "http://test4.dk"
                        });
                });

            modelBuilder.Entity("Blogging.NewDb.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("FK_BlogId");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("FK_BlogId");

                    b.HasIndex("Title")
                        .HasName("Index_Title");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            PostId = 7,
                            Content = "Post Til Data Seeding Test",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_BlogId = 4,
                            Title = "Test 1 Post"
                        },
                        new
                        {
                            PostId = 8,
                            Content = "Post Til Data Seeding Test Ændring",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_BlogId = 5,
                            Title = "Test 2 Post"
                        },
                        new
                        {
                            PostId = 9,
                            Content = "Post Til Data Seeding Test",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_BlogId = 6,
                            Title = "Test 3 Post"
                        },
                        new
                        {
                            PostId = 10,
                            Content = "Post Til Data Seeding Test",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FK_BlogId = 7,
                            Title = "Test 4 Post"
                        });
                });

            modelBuilder.Entity("Blogging.NewDb.Post", b =>
                {
                    b.HasOne("Blogging.NewDb.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("FK_BlogId")
                        .HasConstraintName("ForeignKey_Post_Blog")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
